SELECT nextval('tienda.pusuario_seq');
INSERT INTO TIENDA.PUSUARIO (USUARIO,NOMBRE_USUARIO,CONTRASENA,FECHA_CREACION,ACTIVO)
VALUES(nextval('tienda.pusuario_seq'),'NCARDENAS', 'NATY123','18/03/2025 10:37:50',DEFAULT);

SELECT * FROM TIENDA.PUSUARIO;